# Generated by Django 4.2 on 2023-05-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='song',
        ),
    ]
