# Generated by Django 4.2 on 2023-05-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicService', '0002_alter_album_table_alter_artist_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
