# Generated by Django 4.2 on 2023-05-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicService', '0003_alter_song_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='listenersCount',
        ),
    ]
